const StudentDetails = [
  {
    id:"1",
    name: "mr.balasanthosh",
    rollno: "21BIT003",
    email: "santhos@gmail.com",
    department: "IT",
    year: 6,
    section: "1",
    totalPresent: 11,
    totalAbsent: 20,
    phoneNumber: "xxxxx",
    parentNumber: "xxxxx",
    batch: "2021",
    institute: "institute id",
  },
  {
    id:"2",
    name: "bala",
    rollno: "21BIT004",
    email: "bala@gmail.com",
    department: "IT",
    year: 6,
    section: "1",
    totalPresent: 11,
    totalAbsent: 20,
    phoneNumber: "xxxxx",
    parentNumber: "xxxxx",
    batch: "2021",
    institute: "institute id",
  },
  {
    id:"3",
    name: "john",
    rollno: "21BIT005",
    email: "john@gmail.com",
    department: "IT",
    year: 6,
    section: "1",
    totalPresent: 11,
    totalAbsent: 20,
    phoneNumber: "xxxxx",
    parentNumber: "xxxxx",
    batch: "2021",
    institute: "institute id",
  },
  {
    id:"4",
    name: "mr.mark",
    rollno: "21BIT006",
    email: "mark@gmail.com",
    department: "IT",
    year: 6,
    section: "1",
    totalPresent: 11,
    totalAbsent: 20,
    phoneNumber: "xxxxx",
    parentNumber: "xxxxx",
    batch: "2021",
    institute: "institute id",
  },
  {
    id:"5",
    name: "mr.coolpandi",
    rollno: "21BIT007",
    email: "coolpandi@gmail.com",
    department: "IT",
    year: 6,
    section: "1",
    totalPresent: 11,
    totalAbsent: 20,
    phoneNumber: "xxxxx",
    parentNumber: "xxxxx",
    batch: "2021",
    institute: "institute id",
  },
  {
    id:"1",
    name: "mr.balasanthosh",
    rollno: "21BIT008",
    email: "santhos@gmail.com",
    department: "IT",
    year: 6,
    section: "1",
    totalPresent: 11,
    totalAbsent: 20,
    phoneNumber: "xxxxx",
    parentNumber: "xxxxx",
    batch: "2021",
    institute: "institute id",
  },
  {
    id:"2",
    name: "bala",
    rollno: "21BIT009",
    email: "bala@gmail.com",
    department: "IT",
    year: 6,
    section: "1",
    totalPresent: 11,
    totalAbsent: 20,
    phoneNumber: "xxxxx",
    parentNumber: "xxxxx",
    batch: "2021",
    institute: "institute id",
  },
  {
    id:"3",
    name: "john",
    rollno: "21BIT010",
    email: "john@gmail.com",
    department: "IT",
    year: 6,
    section: "1",
    totalPresent: 11,
    totalAbsent: 20,
    phoneNumber: "xxxxx",
    parentNumber: "xxxxx",
    batch: "2021",
    institute: "institute id",
  },
  {
    id:"4",
    name: "mr.mark",
    rollno: "21BIT011",
    email: "mark@gmail.com",
    department: "IT",
    year: 6,
    section: "1",
    totalPresent: 11,
    totalAbsent: 20,
    phoneNumber: "xxxxx",
    parentNumber: "xxxxx",
    batch: "2021",
    institute: "institute id",
  },
  {
    id:"5",
    name: "mr.coolpandi",
    rollno: "21BIT012",
    email: "coolpandi@gmail.com",
    department: "IT",
    year: 6,
    section: "1",
    totalPresent: 11,
    totalAbsent: 20,
    phoneNumber: "xxxxx",
    parentNumber: "xxxxx",
    batch: "2021",
    institute: "institute id",
  },
];

export default StudentDetails;
